.TH libnmlfi 3 "March 23, 2023" "libaspic" "Module convention" 

.SH NAME
.I nmlfi1
- the non-minimal large field inflation module at decreasing field values

.SH SYNOPSIS
.TP 20
Physical potential (only known as a parametric function):

V(hbar) = M^4 * hbar^p/(1 + hbar^2)^2

with

.RS
phi/Mg = sqrt(6+1/xi) ln{ sqrt[1+(1+6xi)hbar^2] + sqrt[(1+6xi)hbar^3]} + sqrt(6) ln{ sqrt(1+hbar^2)/[sqrt[1+(1+6xi)hbar^2] + sqrt(6xi hbar^2)] }
.RE

.TP
Routine units
.I real(kp)
::
.B x
= phi/Mg
.RS
or
.RE
.RS
.I
real(kp)
::
.B hbar
.RE

.TP
Parameters
.I real(kp)
::
.B xi
.RS
.I real(kp)
::
.B p
.RE

.SH DESCRIPTION
The
.I nmlfi1
module is used for Non-Minimal Large Field Inflation, at decreasing
field values. Inflation ends at a field value 'xend', returned by the
function
.IP
.BR nmlfi1_x_endinf (xi,p)
.P
It proceeds on the left of the potential maximum 'xVmax', when this
one exists, namely for 'p < 4', or at all field values when the
potential has no maximum for 'p >= 4'. However, in the latter
situation, for 'p > p+ ~ 7.46', one should require 'xi < xizero(p)' to
enforce a potential not too steep to support inflation. The functions
returning these quantities can all be found in a common module named
.B nmlficommon
(see below).

Let us stress that the underlying computations of observable
quantities are all done in terms of the parametric field value 'hbar'
and that, calling the standard functions taking as argument 'x' is not
recommended. They are wrappers requiring many numerical inversions
between the canonically normalized field 'x' and 'hbar'. Therefore,
for recurring computations, it is advised to use the parametric field 'hbar'
only. For instance, the parametric field value at the end of inflation
is returned by the function
.IP
.BR nmlfi1_hbar_endinf(xi,p)
.P
while the parametric slow-roll trajectory can be obtained from the
function
.IP
.BR nmlfi1_parametric_hbar_trajectory(bfold,hbarend,xi,p)
.P
all of them taking
.I real(kp)
arguments and returning
.I real(kp)
scalars. It is therefore always possible to never use as an input or
output the actual value of the canonically normalized field.

This model shares many functions with
.I nmlfi2
and
.I nmlfi3
in the module named
.BR nmlficommon .
The value of 'xvMax' is returned by
.BR nmlfi_x_potmax (xi,p)
which is a wrapper over the function
.BR nmlfi_hbar_potmax (xi,p).
This module also contains
.BR nmlfi_xizero (p),
which returns the above-mentionned 'xizero(p)' limiting values
of 'xi'. These functions are imported by directives of this form
.IP
.B use nmlficommon, only : nmlfi_hbar_potmax, nmlfi_xizero
.P
The
.B nmlficommon
module also contains all the functions allowing conversion between
parametric field values 'hbar' and canonically normalized
ones 'phi/Mg'. For instance, it has the
.I real(kp)
functions
.IP
.BR nmlfi_x(hbar,xi)
.RS
.BR nmlfi_hbar(x,xi)
.RE
.P
which return 'x' given 'hbar' and 'xi', or, 'hbar' given 'x' and 'xi'.

.P
Finally,  other numerically convenient functions can be found in
"nmlficommon.f90" in a coding convention very similar to what is done
for Dual Inflation. Please also check the man pages of
.BR aspic_di
for more detailed informations.


.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
