.TH libnmlfi 3 "March 23, 2023" "libaspic" "Module convention" 

.SH NAME
.I nmlfi3
- the non-minimal large field inflation module at increasing field values when inflation does not gracefuly ends

.SH SYNOPSIS
.TP 20
Physical potential (only known as a parametric function):

V(hbar) = M^4 * hbar^p/(1 + hbar^2)^2

with

.RS
phi/Mg = sqrt(6+1/xi) ln{ sqrt[1+(1+6xi)hbar^2] + sqrt[(1+6xi)hbar^3]} + sqrt(6) ln{ sqrt(1+hbar^2)/[sqrt[1+(1+6xi)hbar^2] + sqrt(6xi hbar^2)] }
.RE

.TP
Routine units
.I real(kp)
::
.B x
= phi/Mg
.TP
Parameters
.I real(kp)
::
.B xi
.RS
.I real(kp)
::
.B p
.RS
.RE
.I real(kp)
::
.B xend
.RE

.SH DESCRIPTION
The
.I nmlfi3
module is used for Non-Minimal Large Field Inflation, at increasing
field values, right of the potential maximum 'xVmax'. This one exists
only for 'p < 4' and the
.I nmlfi3
regime is defined as requiring an additional model parameter to end
inflation, 'xend' above. This imposes additional constraints on the
model parameters which are
.IP
.B p > p- ~ 0.54 and p < 4
.RS
.RE
or
.RS
.B p < p- and xi < xizero(p)
.RE

.P
As such, this regime is a three-parameters model. It shares many functions with
.I nmlfi1
and
.I nmlfi2
in the module named
.BR nmlficommon .
The value of 'xvMax' is returned by
.BR nmlfi_x_potmax (xi,p)
which is a wrapper over the function
.BR nmlfi_hbar_potmax (xi,p).
This module also contains
.BR nmlfi_xizero (p),
which returns the above-mentionned 'xizero(p)' limiting values
of 'xi'. These functions are imported by directives of this form
.IP
.B use nmlficommon, only : nmlfi_hbar_potmax, nmlfi_xizero
.P
The
.B nmlficommon
module also contains all the functions allowing conversion between
parametric field values 'hbar' and canonically normalized
ones 'phi/Mg'. For instance, it has the
.I real(kp)
functions
.IP
.BR nmlfi_x(hbar,xi)
.RS
.BR nmlfi_hbar(x,xi)
.RE
.P
which return 'x' given 'hbar' and 'xi', or, 'hbar' given 'x' and 'xi'.

.P
Finally,  other numerically convenient functions can be found in
"nmlficommon.f90" in a coding convention very similar to what is done
for Dual Inflation. Please also check the man pages of
.BR aspic_di
for more detailed informations.


.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
