.TH libsaii 3 "June 18, 2019" "libaspic" "Module convention" 

.SH NAME
.I saii1
- the string axion I inflation module at decreasing field values

.SH SYNOPSIS
.TP
Physical potential
V(phi) = M^4 [ 1 - cos(x) + alpha x sin(x) ]
.TP
Routine units
.I real(kp)
::
.B x
= phi/mu
.TP
Parameters
.I real(kp)
::
.B alpha
.RS
.I real(kp)
::
.B mu/Mp
.RE

.SH DESCRIPTION
The
.I saii1
module is used for the string axion I inflation when inflation occurs
at decreasing field values, namely in the region for which
'x < xVmax', the field value at which the potential is maximal. In this
regime, inflation naturally ends at a field value 'xend' returned by
the
.I real(kp)
function
.BR saii1_x_endinf (alpha,mu).

This model shares a few peculiar functions with
.I saii2
in a module named
.BR saiicommon .
The value of 'xVmax' is returned by the
.I real(kp)
function
.BR saii_x_potmax (alpha).
It can be imported by
.IP
.B use saiicommon, only : saii_x_potmax
.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
