.TH libsdi 3 "April 26, 2016" "libaspic" "Module convention" 

.SH NAME
.I sdi
- the S-dual inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 sech(x)

.TP
Routine units
.I real(kp)
::
.B x
= phi/phi0
.TP
Parameters
.I real(kp)
::
.B phi0
(in Mp units)
.RS
.I real(kp)
::
.B xend
(in phi0 units)

.SH DESCRIPTION
The
.I sdi
module is used for S-dual inflation in the regime where the
accelerating expansion stops by a tachyonic instability at the field
value 'xend', an additional model parameter. This occurs for values
of 'phi0' sufficiently large, the lower bound being given by a
.I real(kp)
function
.IP
.BR sdi_phizeromin()
.P
For values of 'phi0' less than this bound, inflation would naturally
ends but such a situation is ruled out as the inflationary phase ends
up being non slow-rolling in that regime.

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
