.TH libcndi 3 "October 31, 2012" "libaspic" "Module convention" 

.SH NAME
.I cndi
- the non-canonical Kahler inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 / [ 1 + beta cos(alpha x) ]^2
.TP
Routine units
.I real(kp)
::
.B x
= (phi-phi0)/Mp
.TP
Parameters
.I real(kp)
::
.B alpha, beta

.SH DESCRIPTION

To be filled

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
