.TH libsati 3 "April 28, 2016" "libaspic" "Module convention"

.SH NAME
.I sati
- the SuperConformal alpha-attractor T inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 {tanh[ x/sqrt(6 alpha) ]}^(2n)
.TP
Routine units
.I real(kp)
::
.B x
= phi/Mp
.TP
Parameters
.I real(kp)
::
.B alpha, n

.SH DESCRIPTION
The
.I sati
module is used for the superconformal alpha-attractor models described
in
.UR https://arxiv.org/abs/1311.0472
arXiv:1311.0472
.UE
which generalize the so-called T-Models. These ones are recovered by
setting the parameter 'alpha' to unity.

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
