.TH librmi 3 "January 18, 2013" "libaspic" "Module convention" 

.SH NAME
.I rmi1 rmi2 rmi3 rmi4
- the running mass inflation modules

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 { 1 - c/2 [-1/2 + ln(x)](phi0*x)^2 }
.TP
Routine units
.I real(kp)
::
.B x
= phi/phi0
.TP
Parameters
.I real(kp)
::
.B c
.RS
.I real(kp)
::
.B phi0
(in Mp units)
.RE
.RS
.I real(kp)
::
.B xend

.SH DESCRIPTION
The
.I rmi1
module is used for the running mass inflation when 'c > 0' and 'x <
1'.Inflation proceeds at decreasing field values, the value of 'xend'
is an extra-model parameter.

The
.I rmi2
module is used for the running mass inflation when 'c > 0' and 'x >
1'.Inflation proceeds at increasing field values, the value of 'xend'
is an extra-model parameter.

The
.I rmi3
module is used for the running mass inflation when 'c < 0' and 'x <
1'.Inflation proceeds at increasing field values, the value of 'xend'
is an extra-model parameter.

The
.I rmi4
module is used for the running mass inflation when 'c < 0' and 'x >
1'.Inflation proceeds at decreasing field values, the value of 'xend'
is an extra-model parameter.

Shared functions can be found in a module named
.BR rmicommon .

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
