.TH librmi 3 "September 7, 2012" "libaspic" "Module convention" 

.SH NAME
.I rmi
- the running mass inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 { 1 - c/2 [-1/2 + ln(x)](phi0*x)^2 }
.TP
Routine units
.I real(kp)
::
.B x
= phi/phi0
.TP
Parameters
.I real(kp)
::
.B p=2
.RS
.I real(kp)
::
.B phi0
(in Mp units)
.RE
.RS
.I real(kp)
::
.B c


.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
