.TH libahi 3 "September 7, 2012" "libaspic" "Module convention" 

.SH NAME
.I ahi
- the axion hilltop inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 * [ nu0 - 2 cos(phi/phi0) + (pi - phi/phi0) sin(phi/phi0) ]

.TP
Routine units
.I real(kp)
::
.B x
= phi/phi0
.TP
Parameters
.I real(kp)
::
.B phi0


.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
