.TH libahi 3 "April 25, 2016" "libaspic" "Module convention" 

.SH NAME
.I ahi
- the axion hilltop inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 * [ nu0 - 2 cos(phi/f) + (pi - phi/f) sin(phi/f) ]

.TP
Routine units
.I real(kp)
::
.B x
= phi/f
.TP
Parameters
.I real(kp)
::
.B f


.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
