.TH libhf1i 3 "September 7, 2012" "libaspic" "Module convention" 

.SH NAME
.I hf1i
- the horizon flow inflation at first order module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 (1 + A1 x)^2 [1 - 2/3 (A1/(1+A1 x))^2 ]
.TP
Routine units
.I real(kp)
::
.B x
= phi/Mp
.TP
Parameters
.I real(kp)
::
.B A1


.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
