.TH libbi 3 "Aug 19, 2013" "libaspic" "Module convention" 

.SH NAME
.I bi
- the brane inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 [ 1 - x^(-p) ]

.TP
Routine units
.I real(kp)
::
.B x
= phi/mu
.TP
Parameters
.I real(kp)
::
.B p
.RS
.I real(kp)
::
.B mu
(in Mp units)
.RS
.RE
.I real(kp)
::
.B xend

.SH DESCRIPTION
The
.I bi
module is used to describe the class of brane inflation models with 'p
> 0'. Strictly speaking, inflation in the above potential could
naturally end at the field value 'xeps1' for which the first Hubble
flow function equals unity. This value is returned by
.I
real(kp)
function
.IP
.BR bi_x_epsoneunity (p,mu)
.P
Within string motivated scenarios, inflation may also end by brane
annihilation (tachyonic preheating) at a field value 'xstg > xeps1',
which is an additional model parameter. For this reason, the
.I bi
module does not provide a
.BR bi_x_endinf ()
function and has three parameters.

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
