.TH librclfi 3 "December 5, 2019" "libaspic" "Module convention" 

.SH NAME
.I rclfi2
- the radiatively corrected large field inflation 2 module, for
  increasing field values towards the negative minimum of the potential

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 [ x^p + alpha x^4 ln(x) ]
.TP
Routine units
.I real(kp)
::
.B x
= phi/mu
.TP
Parameters
.I real(kp)
::
.B alpha
.RS
.I real(kp)
::
.B p
.RS
.RE
.I real(kp)
::
.B mu/Mp
.RE

.SH DESCRIPTION
The
.I rclfi2
module is used for the radiatively corrected large field inflation
when inflation occurs at increasing field values towards the negative
minimum of the potential, namely in the region for which 'xVmax < x <
xVzero', 'xVmax' being the field value at which the potential is
maximal and 'xVzero' at which it is vanishing and becomes negative. In
this regime, inflation naturally ends at a 'xVmax < xend < xVzero', a
value returned by the
.I real(kp)
function
.IP
.BR rclfi2_x_endinf (alpha,p,mu).
.RS
.RE

The potential does not exhibit a local maximum and a negative minimum
for all values of 'alpha' and 'p'. Therefore, the model exists only
within various disconnected regions of the parameter space. One should
have
.IP
p > 4 and alpha < alpha0(p)
.P
or
.IP
p < 4 and alpha < 0
.P
or
.IP
p < 4 and alpha > alpha0(p)
.P
where 'alpha0' is a function of 'p' coded in the
.I real(kp)
function
.IP
.BR rclfi_alpha_zero (p).
.RS
.RE

available in a module named
.BR rclficommon .
Let us notice that the value of 'p=4' is singular, but in that case
the model becomes
.BR rcqi .
.RS
.RE
The field value at which the potential is maximal is given by the
.I real(kp)
function
.IP
.BR rclfi2_x_potmax(alpha,p,mu) ,
.RS
.RE

and the field value 'xVzero' at which it is vahishing and becomes
negative is returned by the
.I real(kp)
function
.IP
.BR rclfi2_x_potzero(alpha,p,mu) .
.RS
.RE

Because the model is of hilltop type, fine-tuning of the
initial field values may be required for some parameter values. The
module
.BR rclfi2sr
contains various numerical accuracy functions to determine the initial
field values compatible with current machine accuracy, their name is of the
form
.BR *_numacc_*() .
.RS
.RE

Moreover, this model shares a few peculiar functions with
.I rclfi1
.I rclfi3
and
.I rclfi4
in a module named
.BR rclficommon .
Please check the source code of
.B rclficommon
for more details.
.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
