.TH libsbi 3 "October 31, 2012" "libaspic" "Module convention" 

.SH NAME
.I sbi
- the supergravity brane inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 { 1 + [-alpha + beta ln(x) ] x^4 }
.TP
Routine units
.I real(kp)
::
.B x
= phi/Mp
.TP
Parameters
.I real(kp)
::
.B alpha, beta

.SH DESCRIPTION

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
