.TH liblmi2 3 "September 14, 2012" "libaspic" "Module convention" 

.SH NAME
.I lmi2
- the logamediate inflation II module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 x^[4(1-gamma_lmi)] exp[-beta * x^gamma_lmi]
.TP
Routine units
.I real(kp)
::
.B x
= (phi-phi0)/Mp
.TP
Parameters
.I real(kp)
::
.B gamma_lmi, beta


.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
