.TH libmhi 3 "September 7, 2012" "libaspic" "Module convention" 

.SH NAME
.I mhi
- the mutated hilltop inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 * [1 - sech(x)]
.TP
Routine units
.I real(kp)
::
.B x
= phi/mu
.TP
Parameters
.I real(kp)
::
.B mu
(in Mp units)

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
