.TH librpi 3 "October 31, 2012" "libaspic" "Module convention" 

.SH NAME
.I rpi1
- the R + R^2p inflation module at small field values

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 exp(-2x) [ exp(x) - 1 ]^[2p/(2p-1)]
.TP
Routine units
.I real(kp)
::
.B x
= phi/Mp * sqrt(2/3)
.TP
Parameters
.I real(kp)
::
.B p

.SH DESCRIPTION
The
.I rpi1
module is used for the R + R^2p/mu^(4p-2) inflation when 'p > 1' at
small field values, namely in the region for which 'x < xVmax', the
field value at which the potential is maximal. In this regime,
inflation naturally ends at a field value 'xend' returned by the
function
.BR rpi1_x_endinf (p).

This model shares a few peculiar functions with
.I rpi2
and
.I rpi3
in a module named
.BR rpicommon .
The value of 'xvMax' is returned by
.BR rpi_x_potmax (p)
accessible through
.IP
.B use rpicommon, only : rpi_x_potmax
.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
