.TH librpi 3 "August 30, 2013" "libaspic" "Module convention" 

.SH NAME
.I rpi3
- the R + R^2p inflation module for p less than unity

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 exp(-2x) [ exp(x) - 1 ]^[2p/(2p-1)]
.TP
Routine units
.I real(kp)
::
.B x
= phi/Mg * sqrt(2/3)
.TP
Parameters
.I real(kp)
::
.BR p

.SH DESCRIPTION
The
.I rpi3
module is used for the R + R^2p/mu^(4p-2) inflation when 'p < 1'.  In
this regime, inflation ends by slow roll violation.  This model shares
a few peculiar functions with
.I rpi1
and
.I rpi2
in a module named
.BR rpicommon .

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
