.TH librpi 3 "September 7, 2012" "libaspic" "Module convention" 

.SH NAME
.I rpi
- the R + R^p inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 * exp(-2x) * [ exp(x) - 1 ]^(2p/(2p-1))
.TP
Routine units
.I real(kp)
::
.B x
= phi/Mp * sqrt(2/3)
.TP
Parameters
.I real(kp)
::
.B p

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
