.TH libhi 3 "September 7, 2012" "libaspic" "Module convention" 

.SH NAME
.I hi
- the Higgs inflation slow-roll module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 * [1 - exp(-sqrt(2/3) x)]^2
.TP
Routine units
.I real(kp)
::
.B x
= phi/Mp
.TP
Parameters
none

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
