.TH libhi 3 "March 23, 2023" "libaspic" "Module convention" 

.SH NAME
.I hi
- the higgs inflation module (without approximation)

.SH SYNOPSIS
.TP 20
Physical potential (only known as a parametric function):

.RS
V(hbar) = M^4 * [ (hbar^2 - vbar^2)/(1 + hbar^2) ]^2
.RE

where the canonically normalized field in the Einstein frame is

.RS
phi/Mg = sqrt(6+1/xi) ln{ sqrt[1+(1+6xi)hbar^2] + sqrt[(1+6xi)hbar^3]} + sqrt(6) ln{ sqrt(1+hbar^2)/[sqrt[1+(1+6xi)hbar^2] + sqrt(6xi hbar^2)] }
.RE

and where the parametric field value 'hbar' is related to 'H', the
Higgs field in the unitary gauge by,

.RS
hbar = sqrt(xi) H/Mg
.RE

The quantity 'vbar = sqrt(xi) v/Mg' where 'v' is 246GeV in Planck unit
(assuming 'Mg=Mpl, verified at an extreme accuracy for Higgs Inflation).

.TP
Routine units
.I real(kp)
::
.B x
= phi/Mg
.RS
or
.RE
.RS
.I
real(kp)
::
.B hbar
.RE
.TP
Parameters
.I real(kp)
::
.B xi
.RE

.SH DESCRIPTION
The
.I hi
module is used for Higgs Inflation when no other approximations than
slow-roll are made. In particular, it is tinnily different than Starobinsky
Inflation coded in the
.I si
module. The parameter 'xi' is, however, fixed by the amplitude of the
CMB anisotropies while also affecting the Hubble flow functions and
shape of the potential. As such,
.I hi
shares many computational similitude with Dual Inflation coded in the
.I di
module. In particular, the rehating equations are non-standard and
require to numerically solve a system of algebraic equations. This is
done in the
.I hireheat
module.

.SS HISR AND HICOMMON MODULES

Higgs Inflation gracefully ends at field value 'xend' returned by the
.I real(kp)
function
.IP
.BR hi_x_endinf (xi)
.P
Notice the requirement to input 'xi' to get this value (see below). The
underlying calculations use the function
.IP
.BR hi_hbar_endinf (xi)
.P
coded in the
.I hicommon
module and giving as an output 'hbarend', the parametric field value at
which the first Hubble flow function equals unity. The conversion
between field values 'x' and parameter 'hbar' are implemented by
two
.I real(kp)
functions
.IP
.BR hi_x(hbar,xi)
.RS
.BR hi_hbar(x,xi)
.RE
.P
also present in the
.I hicommon.f90
module. All the other functions within the 'hisr' module are standard
but requires as an input the parameter 'xi'. As such, nothing is
enforced to ensure that 'xi' is consistent with the
amplitude of the CMB anisotropies at this stage.


.SS HICOMMON MODULE

This module contains all the "_parametric_" and other low level
functions used to compute the potential, its derivatives as well as
the Hubble flow functions and more. Concerning the potential, they are
.IP
.BR hi_norm_parametric_potential (hbar,xi)
.RE
.RS
.BR hi_norm_deriv_parametric_potential (hbar,xi)
.RE
.RS
.BR hi_norm_deriv_second_parametric_potential (hbar,xi)
.RE
.RS
.BR hi_norm_deriv_third_parametric_potential (hbar,xi)
.RE
.P
and take as argument the parametric field 'hbar' and the
parameter 'xi'. They return the normalized
potential and its successive derivatives with respect to the
parametric field 'hbar'. In order to compute the derivative of the
potential with respect to the canonically normalized field 'x', we also provide the
functions
.IP
.BR hi_deriv_x (hbar,xi)
.RS
.BR hi_deriv_second_x (hbar,xi)
.RE
.P
giving the successive derivatives of 'x' with respect to 'hbar'. The
parametric Hubble flow functions are given by
.IP
.BR hi_parametric_epsilon_one (hbar,xi)
.RS
.BR hi_parametric_epsilon_two (hbar,xi)
.RE
.RS
.BR hi_parametric_epsilon_three (hbar,xi)
.RE
.P
As a result, the observable Hubble flow functions can be directly
computed by calling these functions knowing the value of 'hbarstar'
and 'xistar', see below.

.SS HIREHEAT MODULE

Because the end of inflation, the potential normalization 'M', and the
reheating history depend on 'xi', the functions provided in the
module "direheat.f90" are unlike the standard ones. The module
provides three low level
.I real(kp)
functions
.IP
.BR hi_hbar_star (w,lnRhoReh,Pstar,bfoldstar,xistar)
.RS
.BR hi_hbar_rrad (lnRrad,Pstar,bfoldstar,xistar)
.RE
.RS
.BR hi_hbar_rreh (lnRreh,Pstar,bfoldstar,xistar)
.RE
.P
which all return 'hbarstar', the parametric field value at which the
pivot mode crossed the Hubble radius during inflation, and also, as an
optional output, 'xistar', the value of 'xi' at 'hbarstar' that matches
the amplitude of the CMB anisotropies (set by the input 'Pstar'). As
for the standard case, these three functions solve the reheating
equation from the input of either the couple 'w,lnRhoReh', 'lnRrad'
or 'lnR'. Mind however that
.B hi_rreh_rreh()
requires the input of 'Pstar' as opposed to the standard situation.

.P
From any value of 'hbar', the value of 'xi' matching the CMB
amplitude, can also be determined by using the function
.IP
.BR hi_xi_star(hbar,Pstar)
.P
Notice that changing the reheating history, namely modifying the value
of any reheating parameter, will change the value of 'xistar'.

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
