.TH libwrhi 3 "September 7, 2012" "libaspic" "Module convention" 

.SH NAME
.I wrhi
- the Witten-O'Raifeartaigh Higgs inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 Ln[x]^2
.TP
Routine units
.I real(kp)
::
.B x
= phi/phi0
.TP
Parameters
.I real(kp)
::
.B phi0
(in Mp units)

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
