.TH libhbi 3 "February 10, 2021" "libaspic" "Module convention" 

.SH NAME
.I hbi
- the hyberbolic inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 [ sinh(x)^n ]

.TP
Routine units
.I real(kp)
::
.B x
= phi/mu
.TP
Parameters
.I real(kp)
::
.B n
.RS
.I real(kp)
::
.B mu
(in Mp units)
.RS

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
