.TH libii 3 "September 7, 2012" "libaspic" "Module convention" 

.SH NAME
.I ii
- the intermediate inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 [ x^(-beta) - beta^2/6 x^(-beta-2) ]

.TP
Routine units
.I real(kp)
::
.B x
= (phi-phi0)/Mp
.TP
Parameters
.I real(kp)
::
.B beta
.RS
.I real(kp)
::
.B phi0
(in Mp units)

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
