.TH libnfi 3 "June 04, 2014" "libaspic" "Module convention" 

.SH NAME
.I nfi1
- the N-formalism inflation module for a > 0, b > 1 and x > 0

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 exp( a x^b )
.TP
Routine units
.I real(kp)
::
.B x
= phi/Mp
.TP
Parameters
.I real(kp)
::
.B a, b

.SH DESCRIPTION
The
.I nfi1
module is used for N-formalism inflation when 'a > 0' and 'b > 1', in
the positive field value region 'x > 0'. Inflation proceeds
at increasing field values and naturally ends at 'xend' which is
returned by the
.I real(kp)
function
.IP
.BR nfi1_x_endinf (alpha,beta).
.P
When the parameter 'b' is an even integer, the potential is symmetric
with respect to 'x = 0' and inflation proceeds in the same way in the
negative 'x' domain. When 'b' is an odd integer, the potential has an
inflection point at 'x = 0'. Inflation within the domain 'x > 0' can
still be described by
.I nfi1
but may also evolve from 'x < 0' to 'x > 0'. This particular case is
handled by the
.I nfi7
module.

For '1 < b < 2', the maximal number of efolds from 'x = 0' to 'xend' is
finite. The maximal value of 'a' to obtain 'N' efold of inflation is
returned by the
.I real(kp)
function
.IP
.BR nfi1_amax (N,b)
.P
whereas for 'b > 2' the total number of efolds can be infinite.

Some functions are shared with others
.I nfi
modules in
.BR nficommon
and
.BR nficomreh.

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin

.SH CONTRIBUTORS
Geoffrey Ferraut
