.TH libnfi 3 "June 05, 2014" "libaspic" "Module convention" 

.SH NAME
.I nfi4
- the N-formalism inflation module for a > 0, 0 < b < 1 and a < 0, b < 0

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 exp( a x^b )
.TP
Routine units
.I real(kp)
::
.B x
= phi/Mp
.TP
Parameters
.I real(kp)
::
.B a, b, xend

.SH DESCRIPTION
The
.I nfi4
module is used for N-formalism inflation when 'a > 0' and '0 < b < 1',
or when 'a < 0' and 'b < 0' in the positive field value region 'x >
0'. Inflation proceeds at increasing field values in the domain where
the first Hubble flow function remains less than unity, namely for 'xinimin
< x < +infty', where 'xinimin' is given by the
.I real(kp)
function
.IP
.BR nfi2_xinimin (a,b).
.P
The field value 'xend' at which inflation ends is an additional
model parameter that should lie in the above range. For convenience,
we provide a
.I real(kp)
function
.IP
.BR nfi2_xendmin (N,a,b)
.P
which returns 'xendmin', the minimal value for 'xend' such that
inflation lasts, at least, 'N' efolds between 'xinimin' and 'xendmin'.

When the parameter 'b' is an even integer, the potential is symmetric
with respect to 'x = 0' and inflation proceeds in the same way in the
negative 'x' domain. When 'b' is an odd integer, the potential
supports inflation in the domain 'x < 0' which is described by the
.I nfi7
module for 'b > 0' and the
.I nfi8
module for 'b < 0'.

Some functions are shared with others
.I nfi
modules in
.BR nficommon
and
.BR nficomreh.

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin

.SH CONTRIBUTORS
Geoffrey Ferraut
