.TH librpqti 3 "November 5, 2012" "libaspic" "Module convention" 

.SH NAME
.I rpqti
- the radiative plateau quadratic inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 x^4 (1- 2(1-alpha) ln(x^2) + 2(beta+1) ln(x^2)^2 )
.TP
Routine units
.I real(kp)
::
.B x
= phi/phi0
.TP
Parameters
.I real(kp)
::
.B phi0,alpha,beta


.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
