.TH libsfi 3 "September 7, 2012" "libaspic" "Module convention" 

.SH NAME
.I sfi
- the small field inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 [ 1 - x^p ]

.TP
Routine units
.I real(kp)
::
.B x
= phi/mu
.TP
Parameters
.I real(kp)
::
.B p
.RS
.I real(kp)
::
.B mu
(in Mp units)
.RS

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
