.TH libti 3 "May 14, 2013" "libaspic" "Module convention" 

.SH NAME
.I ti
- the tip inflation module

.SH SYNOPSIS
.TP 20
Physical potential
V(phi) = M^4 [ 1 + cos(x) + alpha sin^2(x) ]
.TP
Routine units
.I real(kp)
::
.B x
= phi/mu
.TP
Parameters
.I real(kp)
::
.B alpha, mu

.SH AUTHORS
Jerome Martin, Christophe Ringeval, Vincent Vennin
